theme: jekyll-theme-minimal
title: FRIENDLY MEMORY
description: Keeping my mind's backup since 2021aa
author: Jorge Salgado

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: " http://lattes.cnpq.br/1267313288850749"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://jorgesalhani.github.io/"

social-network-links:
  email: "jorge.salhani@usp.br"
  github: https://github.com/jorgesalhani
  medium: jorgesalhani
  linkedin: jorgeaugustosalgado
